{% set name = "gala" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76d81896acb8578628a9393d12b88456a07d0a56f1126a941ea2aa75678edc0e

build:
  number: 0
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - numpy
    - gsl
    - extension-helpers
    - cython
    - m2w64-toolchain  # [win]
    - libpython  # [win]
  run:
    - python
    - astropy
    - gsl
    - pyyaml
    - scipy
    - {{ pin_compatible('numpy') }}
    - m2w64-gcc-libs  # [win]

test:
  requires:
    - pytest-astropy
  imports:
    - gala
    - gala.coordinates
    - gala.dynamics
    - gala.dynamics.actionangle._genfunc
    - gala.dynamics.lyapunov
    - gala.dynamics.mockstream
    - gala.integrate
    - gala.integrate.cyintegrators
    - gala.integrate.cyintegrators.dopri
    - gala.integrate.pyintegrators
    - gala.potential
    - gala.potential.frame
    - gala.potential.frame.builtin
    - gala.potential.hamiltonian
    - gala.potential.potential
    - gala.potential.potential.builtin
    - gala.potential.scf

about:
  home: http://gala.adrian.pw/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Galactic and gravitational dynamics in Python
  description: |
    Gala is a Python package for Galactic astronomy and gravitational
    dynamics. The bulk of the package centers around implementations of
    gravitational potentials, numerical integration, and nonlinear dynamics.
  doc_url: http://gala.adrian.pw
  dev_url: https://github.com/adrn/gala

extra:
  recipe-maintainers:
    - mwcraig
    - adrn
