{% set name = "gala" %}
{% set version = "1.3" %}
{% set sha256 = "38d3c4e4ad39fc1b061fd23832df0552a2640be2e468f2d3799349e0e0374d75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py < 35]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
    - numpy >=1.11
  run:
    - python
    - numpy x.x
    - numpy >=1.11
    - networkx
    - h5py
    - matplotlib
    - scipy
    - scikit-image
    - scikit-learn
    - viridis
    - tqdm
    - pyzmq

test:
  requires:
    - pytest
    - coverage
    - nose
    - pytest-cov
  imports:
    - gala.agglo
    - gala.agglo2
    - gala.evaluate
    - gala.features.histogram
  commands:
    # looks like --ignore flags don't work with --pyargs. Comment out for now.
    # - py.test --doctest-modules --pyargs gala --ignore gala/test_package.py --ignore gala/auto.py --ignore gala/segmentation_stitch.py --ignore gala/stack_np.py --ignore gala/valprob.py

about:
  home: https://github.com/janelia-flyem/gala
  license_family: BSD
  license: BSD 3-clause
  license_file: LICENSE
  # Uncomment line below when license.txt is added to PyPI source dist
  # license_file: license.txt
  summary: Automatic segmentation of electron microscopy volumes

  description: |
    Gala is a Python library for performing and evaluating image segmentation,
    distributed under the open-source, 3-clause BSD license. It implements the
    algorithm described in Nunez-Iglesias et al., PLOS ONE, 2013.
  doc_url: https://gala.readthedocs.org
  dev_url: https://github.com/janelia-flyem/gala

extra:
  recipe-maintainers:
    - jni
