{% set name = "astro-gala" %}
{% set version = "0.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "8ee891f7683327f7329dc373aed7769f2d03f23f335fc7f139c3dc9d7ee897c2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1000
  skip: true  # [win or py2k]
  script: "{{ PYTHON }} setup.py install --offline --single-version-externally-managed --record=record.txt"

requirements:
  build:
    {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - astropy
    - six
    - pyyaml
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - gala
    - gala.coordinates
    - gala.dynamics
    - gala.dynamics._genfunc
    - gala.dynamics.lyapunov
    - gala.dynamics.mockstream
    - gala.integrate
    - gala.integrate.cyintegrators
    - gala.integrate.cyintegrators.dopri
    - gala.integrate.pyintegrators
    - gala.potential
    - gala.potential.frame
    - gala.potential.frame.builtin
    - gala.potential.hamiltonian
    - gala.potential.potential
    - gala.potential.potential.builtin

about:
  home: http://gala.adrian.pw/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Galactic and gravitational dynamics in Python
  description: |
    Gala is a Python package for Galactic astronomy and gravitational
    dynamics. The bulk of the package centers around implementations of
    gravitational potentials, numerical integration, and nonlinear dynamics.
  doc_url: http://gala.adrian.pw
  dev_url: https://github.com/adrn/gala

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - adrn
