travis:
  secure:
    BINSTAR_TOKEN: rYfVA4ajQm+jn+p3tvYtzywt8Skn2bFiB/v07WK+dma3MO4zzZVMRLF9F0qvlPmtkRBSbBcazWlJ/o3BbL/w8ZiY/+DQpYqT82eCQcaAUDw9xsgXa2wbq9qVu/i1NWrjaqBqk4vMPi13HDLWPqhTKxonXkA6G/i2InLQYsBtJpOgQ6zozo/LeNit/6KPhFGXp86AmfXwWAhwuPSmkSJEZ4zSfONdb+k25FspCwkJ3ZDZJLb0oew9SbbM8MsDyKzvZT0IhK62lHnfZ7Ps8SAPi3gjMYGZ5eK9wRMRsk0tk035hxdfaRzRQtPSpJsrU5MKRZsTjmYk6VMFHI+lAgV5hsZfGBOQzGP9a9hs8YIBEyxqYXss//upCJk4Y4mTpKnRFewgdbjvof1z6dFymh6Ct/NWN3BoEi1luTem/ZsDE6kHFZ+/H+lAs6iWekcFUe9PbxG67u/wkWThzOTXFJig3BGUWoktgMVBosCMovcMZD7WUVUXmDKEeSggl+c7kC5OJVIXZZAyUMP1+6nui9iWsZGqe3KHpIb+ryKZuCbcKCWLAtk8KtrXzhtBhoKkRV1evw1Mbq7otD7jSCoQME6Ra+hphxJfN3XK49KFXFHz41IGp7sXxwmK3z7O8F8Z6knOlvA0LOZIaELABifXvnlBYUU52AZC5qizWTxLCM9zQHY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
